server:
  port: 8081

oss:
  accessKeyID: 43132414fa
  accessKeySecret: badafadf
  roleArn: badfasfafas
  tokenExpireTime: 098
  endPoint: dfafdas
  policyFile: '{"Statement":[{"Action":["oss:*"],"Effect":"Allow","Resource":["acs:oss:*:*:*"]}],"Version":"1"}'
  bucket: fdadfafa
  region: fdafasfsa
  faceImageUrl: 1431243124








