server:
  port: 8081

oss:
  accessKeyID: 43132414fa
  accessKeySecret: badafadf
  roleArn: badfasfafas
  tokenExpireTime: 098
  endPoint: dfafdas
  policyFile: '3421243124312'
  bucket: fdadfafa
  region: fdafasfsa
  faceImageUrl: 1431243124








